### ISSUE TITLE
Is there support for Windows LAPS?

### ISSUE THREAD

**Issue by needthisforctf** [Seji64/LAPS-WebUI#27]
I'm running LAPS-WebUI using Docker on Linux, connection to ldap goes through, I can login with my username, but search for any ComputerName yields no results despite computers clearly being under SearchBase DN. I low-key suspect that the issue arises due to the fact that I'm using Windows LAPS instead of now deprecated Microsoft LAPS, but can't say for sure. 

My docker-compose:
```yaml
services:
    laps-webui:
        restart: always
        image: ghcr.io/seji64/laps-webui:1.6
        ports:
            - 8080:8080
        environment:
            - Domains__0__Name=Contoso
            - Domains__0__Ldap__Server=dc01.contoso.loc
            - Domains__0__Ldap__Port=636
            - Domains__0__Ldap__UseSSL=true
            - Domains__0__Ldap__TrustAllCertificates=true
            - Domains__0__Ldap__SearchBase='OU=Depts,OU=Contoso,DC=contoso,DC=loc'
```
